[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npx tsc -p server/tsconfig.json"]

[start]
cmd = "node dist-server/server/index.js"
