import "dotenv/config";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const equipment = [
  // ── MACHINES ──────────────────────────────────────────────────────────────
  {
    name: "Leg Press Machine",
    name_es: "Máquina de Prensa de Piernas",
    category: "machine",
    description: "A sled-based resistance machine where you push a weighted platform away from your body using your legs. Targets the quadriceps, hamstrings, and glutes.",
    description_es: "Máquina de resistencia donde empujas una plataforma con peso usando tus piernas. Trabaja cuádriceps, isquiotibiales y glúteos.",
    muscle_groups: ["quadriceps", "hamstrings", "glutes", "calves"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Sit in the machine and place feet shoulder-width apart on the platform.", instruction_es: "Siéntate en la máquina y coloca los pies al ancho de los hombros en la plataforma." },
      { step: 2, instruction: "Unlock the safety bars and slowly lower the platform until knees reach 90 degrees.", instruction_es: "Desbloquea las barras de seguridad y baja la plataforma hasta que las rodillas lleguen a 90 grados." },
      { step: 3, instruction: "Push through your heels to extend your legs and return to the start position.", instruction_es: "Empuja con los talones para extender las piernas y volver a la posición inicial." },
    ],
    safety_tips: ["Never lock your knees at full extension", "Keep your lower back flat against the pad", "Start with light weight to learn the movement"],
    safety_tips_es: ["Nunca bloquees las rodillas en extensión total", "Mantén la zona lumbar pegada al respaldo", "Comienza con poco peso para aprender el movimiento"],
  },
  {
    name: "Lat Pulldown Machine",
    name_es: "Máquina de Jalón al Pecho",
    category: "machine",
    description: "A cable machine that targets the latissimus dorsi. Allows you to simulate a pull-up motion by pulling a bar down to your chest.",
    description_es: "Máquina de cable que trabaja el dorsal ancho. Simula el movimiento de dominadas jalando una barra hacia el pecho.",
    muscle_groups: ["lats", "biceps", "rear deltoids", "rhomboids"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Sit facing the machine and secure your knees under the pads. Grip the bar wider than shoulder-width.", instruction_es: "Siéntate frente a la máquina y asegura las rodillas bajo los cojines. Agarra la barra más ancho que los hombros." },
      { step: 2, instruction: "Lean back slightly and pull the bar down to your upper chest.", instruction_es: "Inclínate ligeramente hacia atrás y jala la barra hacia el pecho superior." },
      { step: 3, instruction: "Slowly return the bar to the top, fully extending your arms.", instruction_es: "Vuelve la barra lentamente arriba, extendiendo completamente los brazos." },
    ],
    safety_tips: ["Avoid pulling the bar behind your neck", "Control the weight on the way up", "Keep core engaged throughout"],
    safety_tips_es: ["Evita jalar la barra detrás del cuello", "Controla el peso al subir", "Mantén el core activado durante todo el movimiento"],
  },
  {
    name: "Chest Press Machine",
    name_es: "Máquina de Press de Pecho",
    category: "machine",
    description: "A seated push machine that isolates the chest muscles, similar to a bench press but with a guided range of motion for safety.",
    description_es: "Máquina de empuje sentado que aísla los músculos del pecho, similar al press de banca pero con movimiento guiado.",
    muscle_groups: ["chest", "triceps", "front deltoids"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Adjust the seat so handles align with your mid-chest.", instruction_es: "Ajusta el asiento para que los mangos queden a la altura del pecho medio." },
      { step: 2, instruction: "Press the handles forward until arms are nearly extended.", instruction_es: "Empuja los mangos hacia adelante hasta que los brazos estén casi extendidos." },
      { step: 3, instruction: "Slowly return to start, feeling the stretch in your chest.", instruction_es: "Vuelve lentamente al inicio, sintiendo el estiramiento en el pecho." },
    ],
    safety_tips: ["Don't arch your back excessively", "Keep shoulders down and back", "Full extension without locking elbows"],
    safety_tips_es: ["No arquees excesivamente la espalda", "Mantén los hombros hacia abajo y atrás", "Extensión completa sin bloquear los codos"],
  },
  {
    name: "Seated Row Machine",
    name_es: "Máquina de Remo Sentado",
    category: "machine",
    description: "A cable-based machine for pulling movements that develop the middle back, rhomboids, and biceps.",
    description_es: "Máquina de cable para movimientos de jalón que desarrollan la espalda media, romboides y bíceps.",
    muscle_groups: ["middle back", "rhomboids", "biceps", "rear deltoids"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Sit upright, feet on foot rests, knees slightly bent.", instruction_es: "Siéntate erguido, pies en los apoyos, rodillas ligeramente dobladas." },
      { step: 2, instruction: "Grip the handle and pull it toward your torso, squeezing shoulder blades together.", instruction_es: "Agarra el mango y jálalo hacia el torso, apretando los omóplatos." },
      { step: 3, instruction: "Return slowly with full arm extension.", instruction_es: "Vuelve lentamente con extensión completa de brazos." },
    ],
    safety_tips: ["Don't round your lower back", "Avoid using momentum", "Keep torso stationary"],
    safety_tips_es: ["No redondees la zona lumbar", "Evita usar impulso", "Mantén el torso estático"],
  },
  {
    name: "Shoulder Press Machine",
    name_es: "Máquina de Press de Hombros",
    category: "machine",
    description: "A guided overhead pressing machine that develops the deltoids and triceps in a safe, controlled path.",
    description_es: "Máquina de press sobre la cabeza que desarrolla los deltoides y tríceps en una trayectoria segura y controlada.",
    muscle_groups: ["deltoids", "triceps", "upper trapezius"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Adjust seat so handles are at shoulder height.", instruction_es: "Ajusta el asiento para que los mangos queden a la altura de los hombros." },
      { step: 2, instruction: "Press the handles overhead until arms are almost fully extended.", instruction_es: "Empuja los mangos sobre la cabeza hasta casi extender los brazos." },
      { step: 3, instruction: "Lower slowly back to shoulder level.", instruction_es: "Baja lentamente de vuelta al nivel de los hombros." },
    ],
    safety_tips: ["Avoid pressing with a heavy arch", "Keep head neutral", "Don't slam the weight stack"],
    safety_tips_es: ["Evita presionar con arqueamiento excesivo", "Mantén la cabeza neutral", "No dejes caer el peso bruscamente"],
  },
  {
    name: "Leg Curl Machine",
    name_es: "Máquina de Curl de Piernas",
    category: "machine",
    description: "An isolation machine targeting the hamstrings by curling the lower leg up against resistance.",
    description_es: "Máquina de aislamiento que trabaja los isquiotibiales curvando la pierna inferior contra la resistencia.",
    muscle_groups: ["hamstrings", "calves"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Lie face down, position roller just above ankle.", instruction_es: "Acuéstate boca abajo, coloca el rodillo justo encima del tobillo." },
      { step: 2, instruction: "Curl your legs upward toward your glutes.", instruction_es: "Curva las piernas hacia arriba en dirección a los glúteos." },
      { step: 3, instruction: "Lower with control to the start position.", instruction_es: "Baja con control a la posición inicial." },
    ],
    safety_tips: ["Don't lift your hips off the pad", "Use full range of motion", "Avoid jerking the weight"],
    safety_tips_es: ["No levantes las caderas del cojín", "Usa el rango completo de movimiento", "Evita mover el peso con brusquedad"],
  },
  {
    name: "Leg Extension Machine",
    name_es: "Máquina de Extensión de Piernas",
    category: "machine",
    description: "An isolation machine that targets the quadriceps by extending the lower leg from a seated position.",
    description_es: "Máquina de aislamiento que trabaja los cuádriceps extendiendo la pierna inferior desde posición sentada.",
    muscle_groups: ["quadriceps"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Sit and place the ankles under the padded roller.", instruction_es: "Siéntate y coloca los tobillos debajo del rodillo acolchado." },
      { step: 2, instruction: "Extend your legs fully upward, squeezing at the top.", instruction_es: "Extiende las piernas completamente hacia arriba, apretando al llegar arriba." },
      { step: 3, instruction: "Lower slowly back to 90 degrees.", instruction_es: "Baja lentamente de vuelta a 90 grados." },
    ],
    safety_tips: ["Avoid using very heavy weights that stress the knee joint", "Keep back against the pad", "Control the eccentric movement"],
    safety_tips_es: ["Evita pesos muy altos que estresen la articulación de la rodilla", "Mantén la espalda contra el respaldo", "Controla el movimiento excéntrico"],
  },
  {
    name: "Pec Deck Machine",
    name_es: "Máquina Pec Deck",
    category: "machine",
    description: "A chest fly machine that isolates the pectoral muscles by bringing the arms together in front of the body.",
    description_es: "Máquina de apertura de pecho que aísla los pectorales juntando los brazos al frente del cuerpo.",
    muscle_groups: ["chest", "front deltoids"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Sit with your back flat, elbows on the pads at shoulder height.", instruction_es: "Siéntate con la espalda recta, codos en los cojines a la altura de los hombros." },
      { step: 2, instruction: "Bring the arms together in front of you, squeezing the chest.", instruction_es: "Junta los brazos al frente, apretando el pecho." },
      { step: 3, instruction: "Open arms back slowly, feeling a stretch in the chest.", instruction_es: "Abre los brazos lentamente, sintiendo el estiramiento en el pecho." },
    ],
    safety_tips: ["Don't go too far back on the opening motion", "Keep shoulders relaxed", "Controlled movements only"],
    safety_tips_es: ["No abras demasiado en el movimiento de apertura", "Relaja los hombros", "Solo movimientos controlados"],
  },
  {
    name: "Smith Machine",
    name_es: "Máquina Smith",
    category: "machine",
    description: "A barbell fixed to vertical guide rails, allowing safe squats, bench presses, and other barbell movements with built-in safety hooks.",
    description_es: "Barra fija a guías verticales que permite sentadillas, press de banca y otros movimientos con ganchos de seguridad incorporados.",
    muscle_groups: ["chest", "quadriceps", "glutes", "shoulders", "triceps"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Set the bar to appropriate height and load desired weight.", instruction_es: "Ajusta la barra a la altura adecuada y carga el peso deseado." },
      { step: 2, instruction: "Rotate the bar to unrack, perform the movement.", instruction_es: "Gira la barra para destrabarla, realiza el movimiento." },
      { step: 3, instruction: "Rotate back to lock and re-rack safely.", instruction_es: "Gira de vuelta para trabar y volver a colocar con seguridad." },
    ],
    safety_tips: ["Always use safety hooks when squatting alone", "The fixed bar path differs from free weights", "Warm up properly before heavy sets"],
    safety_tips_es: ["Siempre usa los ganchos de seguridad al hacer sentadillas solo", "La trayectoria fija difiere de los pesos libres", "Calienta bien antes de series pesadas"],
  },
  {
    name: "Cable Crossover Machine",
    name_es: "Máquina de Cable Crossover",
    category: "cable",
    description: "A dual high-cable station used for chest flyes, tricep pushdowns, bicep curls, and dozens of other exercises with adjustable pulley height.",
    description_es: "Estación de doble cable usada para aperturas de pecho, extensiones de tríceps, curl de bíceps y muchos más ejercicios con polea ajustable.",
    muscle_groups: ["chest", "shoulders", "triceps", "biceps", "core"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Set both pulleys to the desired height and attach handles.", instruction_es: "Ajusta ambas poleas a la altura deseada y coloca los mangos." },
      { step: 2, instruction: "Stand centered between the towers and grip a handle in each hand.", instruction_es: "Párate en el centro entre las torres y agarra un mango con cada mano." },
      { step: 3, instruction: "Perform the chosen exercise with controlled movement through the full range.", instruction_es: "Realiza el ejercicio elegido con movimiento controlado en el rango completo." },
    ],
    safety_tips: ["Adjust pulley height to match the exercise", "Don't release handles abruptly", "Use a weight you can control through the full motion"],
    safety_tips_es: ["Ajusta la altura de la polea según el ejercicio", "No sueltes los mangos bruscamente", "Usa un peso que puedas controlar en todo el movimiento"],
  },
  {
    name: "Hack Squat Machine",
    name_es: "Máquina de Hack Squat",
    category: "machine",
    description: "A guided squat sled that positions the body at an angle, targeting the quadriceps and glutes with less spinal load than a barbell squat.",
    description_es: "Trineo de sentadilla guiado que posiciona el cuerpo en ángulo, trabajando cuádriceps y glúteos con menos carga espinal.",
    muscle_groups: ["quadriceps", "glutes", "hamstrings"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Step onto the platform, shoulders under the pads, back flat.", instruction_es: "Sube a la plataforma, hombros bajo los cojines, espalda recta." },
      { step: 2, instruction: "Unlock and lower until thighs are parallel to the platform.", instruction_es: "Desbloquea y baja hasta que los muslos estén paralelos a la plataforma." },
      { step: 3, instruction: "Push through heels back to start.", instruction_es: "Empuja con los talones de vuelta al inicio." },
    ],
    safety_tips: ["Keep knees aligned with toes", "Don't let heels rise", "Control the descent"],
    safety_tips_es: ["Mantén las rodillas alineadas con los pies", "No dejes que los talones se levanten", "Controla el descenso"],
  },
  // ── FREE WEIGHTS ───────────────────────────────────────────────────────────
  {
    name: "Barbell",
    name_es: "Barra Olímpica",
    category: "free_weight",
    description: "A long steel bar (usually 20 kg / 45 lbs) used with weight plates for compound lifts including squats, deadlifts, bench press, and overhead press.",
    description_es: "Barra de acero larga (normalmente 20 kg / 45 lbs) usada con discos para ejercicios compuestos como sentadillas, peso muerto y press.",
    muscle_groups: ["full body"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Load equal weight on each side and secure with collars.", instruction_es: "Carga peso igual a cada lado y asegura con los cierres." },
      { step: 2, instruction: "Choose the appropriate grip for your exercise.", instruction_es: "Elige el agarre adecuado para tu ejercicio." },
      { step: 3, instruction: "Brace your core and perform the movement with controlled form.", instruction_es: "Activa el core y realiza el movimiento con forma controlada." },
    ],
    safety_tips: ["Always use collars to secure plates", "Never lift to failure without a spotter", "Learn proper form before adding heavy weight"],
    safety_tips_es: ["Siempre usa cierres para asegurar los discos", "Nunca falla sin un compañero de ayuda", "Aprende la forma correcta antes de agregar peso"],
  },
  {
    name: "Dumbbell",
    name_es: "Mancuerna",
    category: "free_weight",
    description: "A short, hand-held weight used for a vast range of exercises. Available in fixed or adjustable versions from 1 to 100+ lbs.",
    description_es: "Peso corto de mano usado para una gran variedad de ejercicios. Disponible en versión fija o ajustable de 1 a 100+ lbs.",
    muscle_groups: ["full body"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Select the appropriate weight for your exercise and goals.", instruction_es: "Selecciona el peso adecuado para tu ejercicio y objetivos." },
      { step: 2, instruction: "Grip the dumbbell firmly in the center of your palm.", instruction_es: "Agarra la mancuerna firmemente en el centro de la palma." },
      { step: 3, instruction: "Perform the movement with a controlled tempo on both phases.", instruction_es: "Realiza el movimiento con tempo controlado en ambas fases." },
    ],
    safety_tips: ["Return dumbbells to the rack after use", "Don't drop dumbbells on the floor", "Use wrist straps only when necessary"],
    safety_tips_es: ["Devuelve las mancuernas al soporte después de usarlas", "No tires las mancuernas al suelo", "Usa correas de muñeca solo cuando sea necesario"],
  },
  {
    name: "EZ Curl Bar",
    name_es: "Barra EZ para Curl",
    category: "free_weight",
    description: "A wavy-shaped short barbell that allows a more natural wrist angle during bicep curls and skull crushers, reducing joint stress.",
    description_es: "Barra corta con forma ondulada que permite un ángulo de muñeca más natural en curls de bíceps y extensiones, reduciendo el estrés articular.",
    muscle_groups: ["biceps", "triceps", "forearms"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Load equal weight on each side and grip the angled sections.", instruction_es: "Carga peso igual a cada lado y agarra las secciones anguladas." },
      { step: 2, instruction: "Stand upright and curl the bar to shoulder height.", instruction_es: "Párate erguido y eleva la barra hasta la altura de los hombros." },
      { step: 3, instruction: "Lower with control to full arm extension.", instruction_es: "Baja con control hasta la extensión completa del brazo." },
    ],
    safety_tips: ["Keep elbows stationary during curls", "Don't swing to generate momentum", "Grip should be firm but not white-knuckle"],
    safety_tips_es: ["Mantén los codos fijos durante los curls", "No balancees para generar impulso", "El agarre debe ser firme pero no excesivo"],
  },
  {
    name: "Kettlebell",
    name_es: "Pesa Rusa (Kettlebell)",
    category: "free_weight",
    description: "A cast-iron weight with a handle, ideal for dynamic exercises like swings, cleans, snatches, and Turkish get-ups.",
    description_es: "Peso de hierro fundido con asa, ideal para ejercicios dinámicos como swings, cleans, arrancadas y Turkish get-ups.",
    muscle_groups: ["glutes", "hamstrings", "core", "shoulders", "back"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Stand with feet hip-width apart, kettlebell between your feet.", instruction_es: "Párate con los pies al ancho de caderas, kettlebell entre los pies." },
      { step: 2, instruction: "Hinge at the hips, grip the handle, and drive hips forward to swing.", instruction_es: "Bisagra en las caderas, agarra el asa y empuja las caderas hacia adelante para hacer el swing." },
      { step: 3, instruction: "Allow the bell to swing back between your legs and repeat.", instruction_es: "Deja que la pesa vuelva entre las piernas y repite." },
    ],
    safety_tips: ["Master the hip hinge before loading heavy", "Keep wrists straight throughout", "Clear enough space around you"],
    safety_tips_es: ["Domina la bisagra de cadera antes de cargar pesado", "Mantén las muñecas rectas durante todo el ejercicio", "Asegúrate de tener suficiente espacio alrededor"],
  },
  {
    name: "Medicine Ball",
    name_es: "Balón Medicinal",
    category: "free_weight",
    description: "A weighted ball used for dynamic strength, power, and core exercises including slams, throws, and rotational movements.",
    description_es: "Pelota con peso usada para ejercicios dinámicos de fuerza, potencia y core incluyendo golpes, lanzamientos y rotaciones.",
    muscle_groups: ["core", "shoulders", "chest", "glutes"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Choose a weight that allows explosive, controlled movements.", instruction_es: "Elige un peso que permita movimientos explosivos y controlados." },
      { step: 2, instruction: "For slams, lift the ball overhead and drive it into the floor.", instruction_es: "Para los golpes, levanta la pelota sobre la cabeza y golpéala contra el suelo." },
      { step: 3, instruction: "Catch or retrieve the ball and repeat with proper form.", instruction_es: "Atrapa o recoge la pelota y repite con buena forma." },
    ],
    safety_tips: ["Check the ball for damage before use", "Ensure adequate ceiling height for overhead movements", "Dry hands prevent slipping"],
    safety_tips_es: ["Revisa la pelota por daños antes de usar", "Asegura altura suficiente para movimientos sobre la cabeza", "Las manos secas evitan resbalones"],
  },
  // ── BENCHES ────────────────────────────────────────────────────────────────
  {
    name: "Flat Bench",
    name_es: "Banco Plano",
    category: "accessory",
    description: "A standard horizontal bench used for bench press, dumbbell exercises, step-ups, and more.",
    description_es: "Banco horizontal estándar usado para press de banca, ejercicios con mancuernas, step-ups y más.",
    muscle_groups: ["chest", "triceps", "shoulders"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Lie flat, feet on the floor, eyes under the bar if using a barbell.", instruction_es: "Acuéstate plano, pies en el suelo, ojos bajo la barra si usas barra." },
      { step: 2, instruction: "Grip the bar slightly wider than shoulder-width.", instruction_es: "Agarra la barra ligeramente más ancho que los hombros." },
      { step: 3, instruction: "Lower the bar to mid-chest and press back up.", instruction_es: "Baja la barra al pecho medio y empuja de vuelta hacia arriba." },
    ],
    safety_tips: ["Use a spotter for heavy lifts", "Keep feet flat on the floor", "Don't bounce the bar off your chest"],
    safety_tips_es: ["Usa un compañero de ayuda para cargas pesadas", "Mantén los pies planos en el suelo", "No rebotas la barra en el pecho"],
  },
  {
    name: "Incline Bench",
    name_es: "Banco Inclinado",
    category: "accessory",
    description: "An adjustable bench set to 30–45 degrees that shifts emphasis to the upper chest and front deltoids during pressing movements.",
    description_es: "Banco ajustable a 30–45 grados que traslada el énfasis al pecho superior y deltoides anteriores en movimientos de press.",
    muscle_groups: ["upper chest", "front deltoids", "triceps"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Set bench to 30–45 degree incline.", instruction_es: "Ajusta el banco a una inclinación de 30–45 grados." },
      { step: 2, instruction: "Sit against the incline, feet flat, and unrack the weight.", instruction_es: "Siéntate contra la inclinación, pies planos, y descarga el peso." },
      { step: 3, instruction: "Lower to upper chest and press to full extension.", instruction_es: "Baja al pecho superior y presiona hasta la extensión completa." },
    ],
    safety_tips: ["Higher incline angles stress the shoulders more", "Ensure both sides of the bar rise evenly", "Control the negative"],
    safety_tips_es: ["Ángulos más altos estresan más los hombros", "Asegura que ambos lados de la barra suban uniformemente", "Controla la fase negativa"],
  },
  {
    name: "Preacher Bench",
    name_es: "Banco Predicador",
    category: "accessory",
    description: "A padded bench that rests arms on an angled pad to isolate the biceps during curl movements, eliminating cheat reps.",
    description_es: "Banco acolchado que apoya los brazos en un cojín angulado para aislar los bíceps en curls, eliminando el impulso trampa.",
    muscle_groups: ["biceps", "brachialis"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Sit and rest the backs of your upper arms against the angled pad.", instruction_es: "Siéntate y apoya la parte trasera de los brazos contra el cojín angulado." },
      { step: 2, instruction: "Hold the bar or dumbbells at full arm extension.", instruction_es: "Sostén la barra o mancuernas con los brazos extendidos." },
      { step: 3, instruction: "Curl upward squeezing the biceps, then lower slowly.", instruction_es: "Eleva apretando los bíceps, luego baja despacio." },
    ],
    safety_tips: ["Don't let the weight fully extend at the bottom with locked elbows", "Keep chest against the pad", "Use a full range of motion"],
    safety_tips_es: ["No permitas que el peso extienda completamente con los codos bloqueados", "Mantén el pecho contra el cojín", "Usa el rango completo de movimiento"],
  },
  // ── CARDIO ─────────────────────────────────────────────────────────────────
  {
    name: "Treadmill",
    name_es: "Caminadora / Cinta de Correr",
    category: "cardio",
    description: "A motorized walking and running belt used for cardiovascular conditioning. Speed and incline are fully adjustable.",
    description_es: "Cinta motorizada para caminar y correr usada para el acondicionamiento cardiovascular. Velocidad e inclinación totalmente ajustables.",
    muscle_groups: ["calves", "hamstrings", "glutes", "core"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Clip the safety cord to your clothing before starting.", instruction_es: "Engancha el cordón de seguridad a tu ropa antes de empezar." },
      { step: 2, instruction: "Start at a slow walking pace to warm up.", instruction_es: "Comienza a un paso lento para calentar." },
      { step: 3, instruction: "Gradually increase speed and/or incline to your target intensity.", instruction_es: "Incrementa gradualmente la velocidad y/o inclinación hasta tu intensidad objetivo." },
    ],
    safety_tips: ["Always attach the emergency stop clip", "Hold the rails only when necessary", "Cool down with a slow walk for 5 minutes"],
    safety_tips_es: ["Siempre engancha el clip de parada de emergencia", "Usa las barandas solo cuando sea necesario", "Enfría con caminata lenta por 5 minutos"],
  },
  {
    name: "Stationary Bike",
    name_es: "Bicicleta Estática",
    category: "cardio",
    description: "A pedal-based cardio machine available in upright and recumbent versions, providing low-impact cardiovascular exercise.",
    description_es: "Máquina de cardio con pedales disponible en versión vertical y reclinada, proporcionando ejercicio cardiovascular de bajo impacto.",
    muscle_groups: ["quadriceps", "hamstrings", "glutes", "calves"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Adjust seat height so leg is almost fully extended at bottom of pedal stroke.", instruction_es: "Ajusta la altura del asiento para que la pierna esté casi extendida en la parte baja del pedaleo." },
      { step: 2, instruction: "Set resistance level and begin pedaling at a comfortable cadence.", instruction_es: "Ajusta el nivel de resistencia y comienza a pedalear a una cadencia cómoda." },
      { step: 3, instruction: "Maintain upright posture and engage core throughout the session.", instruction_es: "Mantén postura erguida y activa el core durante toda la sesión." },
    ],
    safety_tips: ["Adjust seat to avoid knee pain", "Use proper cycling shoes or secure footwear", "Stay hydrated during long sessions"],
    safety_tips_es: ["Ajusta el asiento para evitar dolor de rodillas", "Usa zapatos de ciclismo adecuados o calzado seguro", "Mantente hidratado durante sesiones largas"],
  },
  {
    name: "Elliptical Trainer",
    name_es: "Elíptica",
    category: "cardio",
    description: "A low-impact cardio machine that combines a stepping and cross-country skiing motion to work both the upper and lower body.",
    description_es: "Máquina de cardio de bajo impacto que combina movimiento de escalada y esquí para trabajar el cuerpo completo.",
    muscle_groups: ["quadriceps", "hamstrings", "glutes", "chest", "back", "core"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Step onto the foot platforms and grip the handlebars.", instruction_es: "Sube a las plataformas para pies y agarra las manillas." },
      { step: 2, instruction: "Begin pedaling in a smooth oval motion.", instruction_es: "Comienza a pedalear en un suave movimiento oval." },
      { step: 3, instruction: "Push and pull the handlebars to engage the upper body.", instruction_es: "Empuja y jala las manillas para activar la parte superior del cuerpo." },
    ],
    safety_tips: ["Don't let go of handles while machine is moving", "Adjust stride length if available", "Dismount only after the machine has stopped"],
    safety_tips_es: ["No sueltes las manillas mientras la máquina está en movimiento", "Ajusta la longitud del paso si está disponible", "Desmonta solo después de que la máquina se haya detenido"],
  },
  {
    name: "Rowing Machine",
    name_es: "Máquina de Remo",
    category: "cardio",
    description: "A full-body cardio machine mimicking the rowing stroke. Excellent for building aerobic capacity, back strength, and leg power.",
    description_es: "Máquina de cardio de cuerpo completo que imita la palada del remo. Excelente para capacidad aeróbica, fuerza de espalda y potencia de piernas.",
    muscle_groups: ["back", "legs", "core", "biceps", "shoulders"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Sit on the seat, strap feet in, grip the handle.", instruction_es: "Siéntate, asegura los pies con las correas y agarra el mango." },
      { step: 2, instruction: "Drive with your legs first, then lean back and pull the handle to your lower ribs.", instruction_es: "Empuja primero con las piernas, luego inclínate hacia atrás y jala el mango hacia las costillas bajas." },
      { step: 3, instruction: "Return forward by extending arms first, then swinging body, then bending knees.", instruction_es: "Vuelve al frente extendiendo los brazos primero, luego el cuerpo, luego doblando las rodillas." },
    ],
    safety_tips: ["Never yank the handle with your arms first", "Keep back straight throughout", "Set resistance appropriate to your fitness level"],
    safety_tips_es: ["Nunca jales el mango con los brazos primero", "Mantén la espalda recta durante todo el movimiento", "Ajusta la resistencia adecuada a tu nivel de condición física"],
  },
  {
    name: "Stair Climber",
    name_es: "Escaladora / Stepper",
    category: "cardio",
    description: "A cardiovascular machine that simulates stair climbing, intensely targeting the glutes, quads, and calves while elevating heart rate.",
    description_es: "Máquina cardiovascular que simula la escalada de escaleras, trabajando intensamente glúteos, cuádriceps y pantorrillas.",
    muscle_groups: ["glutes", "quadriceps", "hamstrings", "calves", "core"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Step on the pedals and grip the handrails lightly for balance.", instruction_es: "Sube a los pedales y agarra levemente las barandas para equilibrio." },
      { step: 2, instruction: "Set your desired speed and begin stepping.", instruction_es: "Ajusta tu velocidad deseada y comienza a subir." },
      { step: 3, instruction: "Press through the full foot, not just the ball, for maximum glute activation.", instruction_es: "Empuja con todo el pie, no solo la punta, para máxima activación de glúteos." },
    ],
    safety_tips: ["Don't lean heavily on the handrails", "Start slow to find your rhythm", "Step fully on each pedal"],
    safety_tips_es: ["No te apoyes mucho en las barandas", "Empieza despacio para encontrar tu ritmo", "Pisa completamente en cada pedal"],
  },
  {
    name: "Assault Bike",
    name_es: "Bicicleta de Ataque (Assault Bike)",
    category: "cardio",
    description: "A fan-resistance air bike that uses both arms and legs simultaneously, providing unlimited resistance that scales with effort.",
    description_es: "Bicicleta de ventilador que usa brazos y piernas simultáneamente, proporcionando resistencia ilimitada que escala con el esfuerzo.",
    muscle_groups: ["full body", "cardiovascular system"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Adjust seat height, grip the moving handles.", instruction_es: "Ajusta la altura del asiento, agarra las manillas móviles." },
      { step: 2, instruction: "Begin pedaling and pushing/pulling simultaneously.", instruction_es: "Comienza a pedalear y empujar/jalar simultáneamente." },
      { step: 3, instruction: "Increase speed to ramp up intensity.", instruction_es: "Aumenta la velocidad para subir la intensidad." },
    ],
    safety_tips: ["Pace yourself — intensity rises quickly", "Keep back neutral, don't hunch", "Cool down properly after intervals"],
    safety_tips_es: ["Maneja tu ritmo — la intensidad sube rápido", "Mantén la espalda neutral, no te encojas", "Enfría adecuadamente después de los intervalos"],
  },
  // ── POWER / RACKS ──────────────────────────────────────────────────────────
  {
    name: "Power Rack",
    name_es: "Jaula de Potencia / Power Rack",
    category: "machine",
    description: "A four-post steel cage that allows safe heavy barbell squats, bench press, overhead press, and pull-ups with adjustable safety spotter bars.",
    description_es: "Jaula de acero de cuatro postes que permite sentadillas, press de banca, press de hombros y dominadas de forma segura con barras de seguridad ajustables.",
    muscle_groups: ["full body"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Set J-hooks and safety bars to the correct height for your exercise.", instruction_es: "Ajusta los ganchos y barras de seguridad a la altura correcta para tu ejercicio." },
      { step: 2, instruction: "Load the barbell, unrack, and perform your lift.", instruction_es: "Carga la barra, destraba y realiza tu ejercicio." },
      { step: 3, instruction: "Re-rack safely or allow the bar to rest on safety bars if you fail.", instruction_es: "Vuelve a colocar la barra con seguridad o deja que descanse en las barras de seguridad si fallas." },
    ],
    safety_tips: ["Always set safety bars before squatting alone", "Test safety bar height before loading heavy", "Don't walk the bar out farther than needed"],
    safety_tips_es: ["Siempre ajusta las barras de seguridad antes de hacer sentadillas solo", "Prueba la altura de las barras antes de cargar pesado", "No retrocedas más de lo necesario con la barra"],
  },
  {
    name: "Squat Rack",
    name_es: "Rack de Sentadillas",
    category: "machine",
    description: "A two-post barbell rack designed for squatting. Lighter and more compact than a power rack, often used in commercial gyms.",
    description_es: "Rack de barra de dos postes diseñado para sentadillas. Más ligero y compacto que una jaula de potencia.",
    muscle_groups: ["quadriceps", "glutes", "hamstrings", "core"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Set the J-hooks at upper-chest height.", instruction_es: "Ajusta los ganchos a la altura del pecho superior." },
      { step: 2, instruction: "Bar should rest on traps (low bar) or rear delts (high bar).", instruction_es: "La barra debe descansar en los trapecios (baja) o deltoides posteriores (alta)." },
      { step: 3, instruction: "Step back, feet shoulder-width, squat to parallel or below.", instruction_es: "Retrocede, pies al ancho de hombros, sentadilla a paralelo o más abajo." },
    ],
    safety_tips: ["Use a spotter or full power rack when going heavy", "Always set pins/catchers at appropriate height", "Don't squat in front of mirrors — focus on form"],
    safety_tips_es: ["Usa un compañero o jaula completa cuando cargues pesado", "Ajusta los pines/receptores a la altura adecuada", "No hagas sentadillas frente a espejos — enfócate en la forma"],
  },
  // ── CABLES / FUNCTIONAL ────────────────────────────────────────────────────
  {
    name: "Functional Trainer",
    name_es: "Entrenador Funcional",
    category: "cable",
    description: "A dual adjustable cable station with multiple attachment points and 180° pulley movement. Used for sport-specific and rehabilitation exercises.",
    description_es: "Estación de cable dual ajustable con múltiples puntos de anclaje y movimiento de polea de 180°. Usada para ejercicios específicos de deporte y rehabilitación.",
    muscle_groups: ["full body"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Set cable height and attach appropriate handle.", instruction_es: "Ajusta la altura del cable y coloca el mango adecuado." },
      { step: 2, instruction: "Step away from the machine to create tension.", instruction_es: "Aléjate de la máquina para crear tensión." },
      { step: 3, instruction: "Perform the movement pattern through full range.", instruction_es: "Realiza el patrón de movimiento en el rango completo." },
    ],
    safety_tips: ["Ensure carabiners are fully locked before use", "Start lighter than you think you need", "Maintain balance throughout the movement"],
    safety_tips_es: ["Asegura que los mosquetones estén completamente bloqueados antes de usar", "Empieza más ligero de lo que crees necesitar", "Mantén el equilibrio durante todo el movimiento"],
  },
  {
    name: "Battle Ropes",
    name_es: "Cuerdas de Batalla",
    category: "accessory",
    description: "Heavy, thick ropes anchored to a wall or post used for high-intensity interval training, improving power, endurance, and core stability.",
    description_es: "Cuerdas gruesas y pesadas ancladas a una pared o poste para entrenamiento de alta intensidad, mejorando potencia, resistencia y estabilidad del core.",
    muscle_groups: ["shoulders", "arms", "core", "back"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Stand with slight knee bend, hold one end of rope in each hand.", instruction_es: "Párate con una ligera flexión de rodillas, sostén un extremo de la cuerda en cada mano." },
      { step: 2, instruction: "Alternate raising and lowering arms to create waves down the rope.", instruction_es: "Alterna subir y bajar los brazos para crear ondas a lo largo de la cuerda." },
      { step: 3, instruction: "Maintain a strong plank-like core position throughout.", instruction_es: "Mantén una posición de core firme tipo plancha durante todo el ejercicio." },
    ],
    safety_tips: ["Warm up shoulders before intense rope work", "Keep knees soft to protect the lower back", "Don't let rope snap back and hit you"],
    safety_tips_es: ["Calienta los hombros antes del trabajo intenso con cuerdas", "Mantén las rodillas suaves para proteger la zona lumbar", "No dejes que la cuerda rebote y te golpee"],
  },
  // ── ACCESSORIES / BODYWEIGHT ───────────────────────────────────────────────
  {
    name: "Pull-up Bar",
    name_es: "Barra de Dominadas",
    category: "accessory",
    description: "A horizontal bar used for pull-ups, chin-ups, and hanging core exercises. Can be mounted on a wall, door frame, or power rack.",
    description_es: "Barra horizontal para dominadas, chin-ups y ejercicios colgantes de core. Se puede montar en pared, marco de puerta o rack.",
    muscle_groups: ["lats", "biceps", "rear deltoids", "core"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Grip the bar slightly wider than shoulder-width, palms facing away.", instruction_es: "Agarra la barra ligeramente más ancho que los hombros, palmas hacia afuera." },
      { step: 2, instruction: "Hang fully, then pull yourself up until chin clears the bar.", instruction_es: "Cuelga completamente, luego jálate hasta que el mentón supere la barra." },
      { step: 3, instruction: "Lower yourself with control until arms are fully extended.", instruction_es: "Bájate con control hasta que los brazos estén completamente extendidos." },
    ],
    safety_tips: ["Don't kip or swing unless intentional", "Full dead hang between reps for maximum range", "Use assistance bands if needed to build strength"],
    safety_tips_es: ["No balancees a menos que sea intencional", "Cuelga completamente entre repeticiones para el rango máximo", "Usa bandas de asistencia si necesitas construir fuerza"],
  },
  {
    name: "Dip Bars",
    name_es: "Barras de Fondos (Dips)",
    category: "accessory",
    description: "Parallel bars used for tricep dips and chest dips, one of the best bodyweight exercises for upper body pressing strength.",
    description_es: "Barras paralelas usadas para fondos de tríceps y pecho, uno de los mejores ejercicios de peso corporal para la fuerza de empuje del tren superior.",
    muscle_groups: ["triceps", "chest", "front deltoids"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Grip bars with straight arms, legs crossed behind.", instruction_es: "Agarra las barras con brazos rectos, piernas cruzadas detrás." },
      { step: 2, instruction: "Lower until elbows reach 90 degrees.", instruction_es: "Baja hasta que los codos lleguen a 90 grados." },
      { step: 3, instruction: "Press back up to straight arms without locking out.", instruction_es: "Empuja de vuelta a brazos rectos sin bloquear los codos." },
    ],
    safety_tips: ["Don't dip below 90 degrees if you have shoulder issues", "Lean forward for chest emphasis; upright for triceps", "Use dip belt to add weight progressively"],
    safety_tips_es: ["No bajes de 90 grados si tienes problemas de hombros", "Inclínate adelante para énfasis en pecho; erguido para tríceps", "Usa cinturón de fondos para agregar peso progresivamente"],
  },
  {
    name: "TRX Suspension Trainer",
    name_es: "TRX Entrenador en Suspensión",
    category: "accessory",
    description: "Adjustable straps anchored overhead that use bodyweight and gravity for hundreds of functional exercises.",
    description_es: "Correas ajustables ancladas en lo alto que usan el peso corporal y la gravedad para cientos de ejercicios funcionales.",
    muscle_groups: ["full body", "core"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Anchor the TRX to a secure overhead point.", instruction_es: "Ancla el TRX a un punto elevado seguro." },
      { step: 2, instruction: "Adjust length based on exercise requirements.", instruction_es: "Ajusta la longitud según los requisitos del ejercicio." },
      { step: 3, instruction: "Maintain body alignment — the straighter your body, the harder the exercise.", instruction_es: "Mantén la alineación corporal — cuanto más recto el cuerpo, más difícil el ejercicio." },
    ],
    safety_tips: ["Check anchor point can support your body weight plus force", "Keep core braced at all times", "Progress gradually by changing body angle"],
    safety_tips_es: ["Verifica que el punto de anclaje soporte tu peso corporal más la fuerza", "Mantén el core activado en todo momento", "Progresa gradualmente cambiando el ángulo corporal"],
  },
  {
    name: "Resistance Bands",
    name_es: "Bandas de Resistencia",
    category: "accessory",
    description: "Elastic bands providing variable resistance. Used for warm-ups, rehabilitation, strength training, and as assistance for bodyweight exercises.",
    description_es: "Bandas elásticas que proporcionan resistencia variable. Usadas para calentamiento, rehabilitación, fuerza y como asistencia en ejercicios de peso corporal.",
    muscle_groups: ["full body"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Select appropriate resistance level (light/medium/heavy).", instruction_es: "Selecciona el nivel de resistencia adecuado (ligero/medio/pesado)." },
      { step: 2, instruction: "Anchor or hold the band as required for your exercise.", instruction_es: "Ancla o sostén la banda según tu ejercicio." },
      { step: 3, instruction: "Perform the movement through full range, controlling the release.", instruction_es: "Realiza el movimiento en rango completo, controlando la vuelta." },
    ],
    safety_tips: ["Inspect bands for tears or nicks before every use", "Never release a loaded band toward your face", "Store away from direct sunlight to prevent degradation"],
    safety_tips_es: ["Inspecciona las bandas por roturas antes de cada uso", "Nunca sueltes una banda cargada hacia tu cara", "Guárdalas lejos de la luz solar directa para evitar degradación"],
  },
  {
    name: "Foam Roller",
    name_es: "Rodillo de Espuma (Foam Roller)",
    category: "accessory",
    description: "A cylindrical foam tool used for self-myofascial release (SMR), helping to reduce muscle soreness and improve mobility.",
    description_es: "Herramienta cilíndrica de espuma usada para liberación miofascial (SMR), ayudando a reducir el dolor muscular y mejorar la movilidad.",
    muscle_groups: ["full body", "fascia"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Place the roller under the target muscle group.", instruction_es: "Coloca el rodillo debajo del grupo muscular objetivo." },
      { step: 2, instruction: "Use body weight to apply pressure and slowly roll along the muscle.", instruction_es: "Usa el peso corporal para aplicar presión y rueda lentamente a lo largo del músculo." },
      { step: 3, instruction: "Pause on tender spots for 20–30 seconds.", instruction_es: "Haz pausa en los puntos sensibles durante 20–30 segundos." },
    ],
    safety_tips: ["Avoid rolling directly over joints or bones", "Don't roll an acutely injured area", "Breathe deeply to help release tension"],
    safety_tips_es: ["Evita rodar directamente sobre articulaciones o huesos", "No hagas rodado sobre una zona con lesión aguda", "Respira profundo para ayudar a liberar la tensión"],
  },
  {
    name: "Ab Roller",
    name_es: "Rueda Abdominal",
    category: "accessory",
    description: "A small wheel with handles used for rollout exercises that intensely engage the core, hip flexors, and shoulder stabilizers.",
    description_es: "Pequeña rueda con mangos para ejercicios de rodada que trabajan intensamente el core, flexores de cadera y estabilizadores de hombros.",
    muscle_groups: ["core", "hip flexors", "shoulders", "lats"],
    difficulty: "advanced",
    tutorial_steps: [
      { step: 1, instruction: "Kneel on a mat, grip the roller with both hands.", instruction_es: "Arrodíllate en un tapete, agarra la rueda con ambas manos." },
      { step: 2, instruction: "Roll forward slowly until your body is parallel to the floor.", instruction_es: "Rueda hacia adelante lentamente hasta que tu cuerpo esté paralelo al suelo." },
      { step: 3, instruction: "Contract your core and pull back to start.", instruction_es: "Contrae el core y jala de vuelta al inicio." },
    ],
    safety_tips: ["Never do full rollouts without a solid plank foundation", "Keep lower back from hyperextending", "Start with partial range until you build strength"],
    safety_tips_es: ["Nunca hagas rodadas completas sin una base sólida de plancha", "Evita hiperextender la zona lumbar", "Comienza con rango parcial hasta construir fuerza"],
  },
  {
    name: "Jump Rope",
    name_es: "Cuerda para Saltar",
    category: "cardio",
    description: "A skipping rope used for cardiovascular conditioning, coordination, and footwork training. One of the most efficient calorie-burning tools.",
    description_es: "Cuerda para saltar usada para acondicionamiento cardiovascular, coordinación y agilidad. Una de las herramientas más eficientes para quemar calorías.",
    muscle_groups: ["calves", "shoulders", "core", "cardiovascular system"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Adjust rope length to reach your armpits when standing on the middle.", instruction_es: "Ajusta la longitud para que llegue a tus axilas cuando estés parado en el centro." },
      { step: 2, instruction: "Hold handles at hip level, spin the rope using your wrists.", instruction_es: "Sostén los mangos a nivel de caderas, gira la cuerda usando las muñecas." },
      { step: 3, instruction: "Jump 1–2 inches off the floor, landing softly on the balls of your feet.", instruction_es: "Salta 1–2 pulgadas del suelo, aterrizando suavemente en los metatarsos." },
    ],
    safety_tips: ["Jump on a sprung wooden floor or rubber mat, not concrete", "Wear supportive footwear", "Keep jumps small to reduce joint impact"],
    safety_tips_es: ["Salta en suelo de madera o colchoneta de goma, no en concreto", "Usa calzado con soporte adecuado", "Mantén los saltos pequeños para reducir el impacto articular"],
  },
  {
    name: "Weight Belt",
    name_es: "Cinturón de Halterofilia",
    category: "accessory",
    description: "A thick leather or nylon belt worn around the waist to increase intra-abdominal pressure during heavy compound lifts.",
    description_es: "Cinturón grueso de cuero o nylon usado alrededor de la cintura para aumentar la presión intraabdominal durante levantamientos compuestos pesados.",
    muscle_groups: ["core", "spine stabilizers"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Place the belt around your natural waist (above hip bones).", instruction_es: "Coloca el cinturón alrededor de tu cintura natural (por encima de los huesos de la cadera)." },
      { step: 2, instruction: "Tighten so one to two fingers fit underneath.", instruction_es: "Ajústalo para que quepan uno o dos dedos por debajo." },
      { step: 3, instruction: "Take a big breath before the lift to brace against the belt.", instruction_es: "Toma una respiración profunda antes del levantamiento para empujar contra el cinturón." },
    ],
    safety_tips: ["Don't use a belt for every set — build natural core strength too", "Don't overtighten to the point of restricting breathing", "Belt doesn't replace proper bracing technique"],
    safety_tips_es: ["No uses el cinturón en cada serie — construye también fuerza natural del core", "No lo aprietes tanto que restrinja la respiración", "El cinturón no reemplaza la técnica correcta de activación del core"],
  },
  {
    name: "Weight Plates",
    name_es: "Discos de Peso",
    category: "free_weight",
    description: "Iron or bumper plates loaded onto barbells or used independently. Available in standard (1-inch) and Olympic (2-inch) hole sizes.",
    description_es: "Discos de hierro o goma para cargar en barras o usar independientemente. Disponibles en medida estándar (1 pulgada) y olímpica (2 pulgadas).",
    muscle_groups: ["full body"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Select matching plates for both sides of the barbell.", instruction_es: "Selecciona discos iguales para ambos lados de la barra." },
      { step: 2, instruction: "Slide onto the barbell sleeve and secure with a collar.", instruction_es: "Desliza en el brazo de la barra y asegura con un cierre." },
      { step: 3, instruction: "Ensure even loading before lifting.", instruction_es: "Asegura que la carga sea uniforme antes de levantar." },
    ],
    safety_tips: ["Always use collars to prevent plates sliding off", "Stack plates properly when not in use", "Bumper plates are safer for drops"],
    safety_tips_es: ["Siempre usa cierres para evitar que los discos se deslicen", "Apila los discos correctamente cuando no los uses", "Los discos de goma son más seguros para soltar al piso"],
  },
  {
    name: "Hex Bar / Trap Bar",
    name_es: "Barra Hexagonal / Trap Bar",
    category: "free_weight",
    description: "A hexagonal-shaped barbell you stand inside of, allowing a more neutral spine position for deadlifts with reduced lower back stress.",
    description_es: "Barra hexagonal dentro de la cual te paras, permitiendo una posición más neutral de la columna para el peso muerto con menos estrés lumbar.",
    muscle_groups: ["glutes", "hamstrings", "quadriceps", "traps", "forearms"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Stand inside the frame with feet hip-width apart.", instruction_es: "Párate dentro del marco con los pies al ancho de caderas." },
      { step: 2, instruction: "Grip the handles and hinge at the hips, keeping chest tall.", instruction_es: "Agarra los mangos y haz bisagra en las caderas, manteniendo el pecho alto." },
      { step: 3, instruction: "Drive through the floor, extending hips and knees to stand up.", instruction_es: "Empuja contra el suelo, extendiendo caderas y rodillas para pararte." },
    ],
    safety_tips: ["Ideal for beginners learning deadlift mechanics", "Keep the bar close to your body", "Never round the lower back under load"],
    safety_tips_es: ["Ideal para principiantes aprendiendo la mecánica del peso muerto", "Mantén la barra cerca del cuerpo", "Nunca redondees la zona lumbar bajo carga"],
  },
  {
    name: "Cable Machine",
    name_es: "Máquina de Cable",
    category: "cable",
    description: "A pulley-based machine with a weight stack that provides constant tension throughout the range of motion for exercises like pushdowns and curls.",
    description_es: "Máquina con sistema de poleas y pesas que proporciona tensión constante en todo el rango de movimiento para ejercicios como extensiones y curl.",
    muscle_groups: ["full body"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Set the pin in the weight stack to your desired load.", instruction_es: "Coloca el pin en la pila de pesas al peso deseado." },
      { step: 2, instruction: "Attach your preferred handle or rope accessory.", instruction_es: "Conecta el mango o accesorio de cuerda que prefieras." },
      { step: 3, instruction: "Stand at appropriate distance and perform the exercise.", instruction_es: "Párate a la distancia adecuada y realiza el ejercicio." },
    ],
    safety_tips: ["Never drop the weight stack — control the eccentric", "Check that the pin is fully inserted", "Keep movements controlled"],
    safety_tips_es: ["Nunca dejes caer la pila de pesas — controla la fase excéntrica", "Verifica que el pin esté completamente insertado", "Mantén los movimientos controlados"],
  },
  {
    name: "T-Bar Row",
    name_es: "Remo en T (T-Bar Row)",
    category: "free_weight",
    description: "A compound back exercise performed with one end of a barbell anchored and the other end loaded, using a V-handle or chest pad.",
    description_es: "Ejercicio compuesto de espalda con un extremo de la barra anclado y el otro cargado con peso, usando un mango en V o cojín de pecho.",
    muscle_groups: ["lats", "middle back", "rhomboids", "biceps"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Straddle the bar, grip the handle, slight forward lean.", instruction_es: "A horcajadas sobre la barra, agarra el mango, inclínate ligeramente hacia adelante." },
      { step: 2, instruction: "Row the bar to your chest, keeping elbows close.", instruction_es: "Jala la barra hacia el pecho, manteniendo los codos cerca." },
      { step: 3, instruction: "Lower with control to full arm extension.", instruction_es: "Baja con control hasta la extensión completa de brazos." },
    ],
    safety_tips: ["Keep back flat — not rounded under load", "Hinge from hips not waist", "Brace core throughout"],
    safety_tips_es: ["Mantén la espalda recta — no redondees bajo carga", "Bisagra desde las caderas no desde la cintura", "Activa el core durante todo el movimiento"],
  },
  {
    name: "Preacher Curl Machine",
    name_es: "Máquina de Curl Predicador",
    category: "machine",
    description: "A machine version of the preacher curl that locks arms in place on a pad to isolate biceps with a fixed range of motion.",
    description_es: "Versión en máquina del curl predicador que fija los brazos en un cojín para aislar los bíceps con un rango de movimiento fijo.",
    muscle_groups: ["biceps", "brachialis"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Adjust the seat so your armpits rest on top of the pad.", instruction_es: "Ajusta el asiento para que las axilas descansen en la parte superior del cojín." },
      { step: 2, instruction: "Grip the handles and curl toward your shoulders.", instruction_es: "Agarra los mangos y eleva hacia los hombros." },
      { step: 3, instruction: "Lower slowly to full extension.", instruction_es: "Baja despacio hasta la extensión completa." },
    ],
    safety_tips: ["Don't hyperextend at the bottom", "Squeeze at the top of the movement", "Keep wrists neutral"],
    safety_tips_es: ["No hiperextiendas al bajar", "Aprieta en la parte superior del movimiento", "Mantén las muñecas neutrales"],
  },
  {
    name: "Glute Kickback Machine",
    name_es: "Máquina de Patada de Glúteo",
    category: "machine",
    description: "A machine that isolates the glutes by performing a hip extension movement against resistance.",
    description_es: "Máquina que aísla los glúteos realizando una extensión de cadera contra resistencia.",
    muscle_groups: ["glutes", "hamstrings"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Place the padded lever against the back of your thigh.", instruction_es: "Coloca la palanca acolchada contra la parte trasera del muslo." },
      { step: 2, instruction: "Extend your leg back, squeezing the glute at full extension.", instruction_es: "Extiende la pierna hacia atrás, apretando el glúteo en la extensión completa." },
      { step: 3, instruction: "Return with control to the start position.", instruction_es: "Vuelve con control a la posición inicial." },
    ],
    safety_tips: ["Keep hips square throughout", "Don't hyperextend the lower back", "Squeeze glutes at peak contraction"],
    safety_tips_es: ["Mantén las caderas alineadas durante todo el movimiento", "No hiperextiendas la zona lumbar", "Aprieta los glúteos en la contracción máxima"],
  },
  {
    name: "Assisted Pull-up Machine",
    name_es: "Máquina de Dominadas Asistidas",
    category: "machine",
    description: "A machine with a counterweight platform that offsets a portion of your body weight, making pull-ups and dips accessible for beginners.",
    description_es: "Máquina con plataforma de contrapeso que compensa parte del peso corporal, haciendo las dominadas y fondos accesibles para principiantes.",
    muscle_groups: ["lats", "biceps", "chest", "triceps"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Set the counterweight (higher weight = more assistance).", instruction_es: "Ajusta el contrapeso (más peso = más asistencia)." },
      { step: 2, instruction: "Kneel or stand on the platform and grip the bars.", instruction_es: "Arrodíllate o párate en la plataforma y agarra las barras." },
      { step: 3, instruction: "Perform the pull-up or dip with full range of motion.", instruction_es: "Realiza la dominada o el fondo con el rango completo de movimiento." },
    ],
    safety_tips: ["Reduce assistance weight gradually to build real strength", "Don't bounce at the bottom", "Full lockout at the top for pull-ups"],
    safety_tips_es: ["Reduce el contrapeso gradualmente para construir fuerza real", "No rebotas al fondo", "Extensión completa arriba en las dominadas"],
  },
  {
    name: "Hip Thrust Machine",
    name_es: "Máquina de Hip Thrust",
    category: "machine",
    description: "A dedicated machine for hip thrust exercises, allowing heavy glute loading in a controlled range of motion.",
    description_es: "Máquina dedicada para ejercicios de hip thrust, permitiendo carga pesada de glúteos en un rango controlado.",
    muscle_groups: ["glutes", "hamstrings", "core"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Sit with upper back against the padded bench, pad across hips.", instruction_es: "Siéntate con la espalda alta contra el banco acolchado, cojín a través de las caderas." },
      { step: 2, instruction: "Drive hips upward until body forms a straight line from knees to shoulders.", instruction_es: "Empuja las caderas hacia arriba hasta que el cuerpo forme una línea recta de rodillas a hombros." },
      { step: 3, instruction: "Lower with control and repeat.", instruction_es: "Baja con control y repite." },
    ],
    safety_tips: ["Keep chin tucked to avoid neck strain", "Squeeze glutes at top, not just extend hips", "Ensure the pad rests on the hip crease"],
    safety_tips_es: ["Mantén la barbilla recogida para evitar tensión en el cuello", "Aprieta los glúteos arriba, no solo extiendas las caderas", "Asegura que el cojín descanse en el pliegue de la cadera"],
  },
  {
    name: "Reverse Hyper Machine",
    name_es: "Máquina de Hiperextensión Inversa",
    category: "machine",
    description: "A machine where you lie face down and swing legs upward to target the glutes, hamstrings, and lumbar extensors while decompressing the spine.",
    description_es: "Máquina donde te acuestas boca abajo y elevas las piernas para trabajar glúteos, isquiotibiales y extensores lumbares mientras descomprime la columna.",
    muscle_groups: ["glutes", "hamstrings", "lower back"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Lie face down over the pad, gripping the handles, legs hanging.", instruction_es: "Acuéstate boca abajo sobre el cojín, agarra los mangos, piernas colgando." },
      { step: 2, instruction: "Swing legs upward using glutes and hamstrings.", instruction_es: "Eleva las piernas usando glúteos e isquiotibiales." },
      { step: 3, instruction: "Lower with control in a pendulum motion.", instruction_es: "Baja con control en movimiento de péndulo." },
    ],
    safety_tips: ["Don't hyperextend excessively at the top", "Start with bodyweight only", "Excellent for rehab, but consult a physio if injured"],
    safety_tips_es: ["No hiperextiendas excesivamente arriba", "Empieza solo con el peso corporal", "Excelente para rehabilitación, pero consulta fisioterapeuta si estás lesionado"],
  },
  {
    name: "Plyo Box",
    name_es: "Caja de Pliometría",
    category: "accessory",
    description: "A sturdy box used for box jumps, step-ups, depth jumps, and seated box squats to develop explosive leg power.",
    description_es: "Caja resistente usada para saltos, escalones, saltos de profundidad y sentadillas en caja para desarrollar potencia explosiva.",
    muscle_groups: ["glutes", "quadriceps", "hamstrings", "calves"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Stand facing the box, feet hip-width apart.", instruction_es: "Párate frente a la caja, pies al ancho de caderas." },
      { step: 2, instruction: "Bend knees, swing arms back, and jump explosively onto the box.", instruction_es: "Dobla las rodillas, balancea los brazos hacia atrás y salta explosivamente a la caja." },
      { step: 3, instruction: "Land softly, stand tall, then step down carefully.", instruction_es: "Aterriza suavemente, párate erguido, luego baja cuidadosamente." },
    ],
    safety_tips: ["Step down, don't jump down — knee injuries happen on landing", "Ensure the box is on a non-slip surface", "Build up box height gradually"],
    safety_tips_es: ["Baja caminando, no saltando — las lesiones de rodilla ocurren al aterrizar", "Asegura que la caja esté en superficie antideslizante", "Aumenta la altura de la caja gradualmente"],
  },
  {
    name: "GHD Machine",
    name_es: "Máquina GHD (Glute-Ham Developer)",
    category: "machine",
    description: "A glute-ham developer machine for posterior chain exercises including GHD sit-ups, back extensions, and glute-ham raises.",
    description_es: "Máquina de desarrollo glúteo-isquiotibial para ejercicios de la cadena posterior incluyendo sit-ups GHD, extensiones de espalda y elevaciones.",
    muscle_groups: ["hamstrings", "glutes", "lower back", "core"],
    difficulty: "advanced",
    tutorial_steps: [
      { step: 1, instruction: "Position hips on pad, feet secured under the rollers.", instruction_es: "Posiciona las caderas en el cojín, pies asegurados bajo los rodillos." },
      { step: 2, instruction: "Lower torso toward the floor in a controlled arc.", instruction_es: "Baja el torso hacia el suelo en un arco controlado." },
      { step: 3, instruction: "Contract hamstrings and glutes to return to upright.", instruction_es: "Contrae isquiotibiales y glúteos para volver a la posición erguida." },
    ],
    safety_tips: ["GHD sit-ups cause intense DOMS — start with very few reps", "Ensure correct foot position before beginning", "Spotter recommended for beginners"],
    safety_tips_es: ["Los sit-ups GHD causan DOMS intenso — empieza con muy pocas repeticiones", "Asegura la posición correcta del pie antes de empezar", "Se recomienda compañero de ayuda para principiantes"],
  },
  {
    name: "Dumbbell Rack",
    name_es: "Soporte de Mancuernas",
    category: "accessory",
    description: "A storage and organization unit holding multiple pairs of dumbbells in ascending order for quick selection during workouts.",
    description_es: "Unidad de almacenamiento que sostiene múltiples pares de mancuernas en orden ascendente para selección rápida durante los entrenamientos.",
    muscle_groups: ["full body"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Select the appropriate dumbbell pair for your exercise.", instruction_es: "Selecciona el par de mancuernas adecuado para tu ejercicio." },
      { step: 2, instruction: "Always return dumbbells to their correct slot after use.", instruction_es: "Siempre devuelve las mancuernas a su lugar correcto después de usarlas." },
      { step: 3, instruction: "Pick up from the ends of the handles, not the head of the weight.", instruction_es: "Recoge desde los extremos de los mangos, no desde la cabeza del peso." },
    ],
    safety_tips: ["Never drop dumbbells near the rack", "Heaviest dumbbells on lowest shelves", "Keep floor around the rack clear"],
    safety_tips_es: ["Nunca tires mancuernas cerca del soporte", "Las más pesadas en las repisas más bajas", "Mantén el suelo alrededor del soporte despejado"],
  },
  {
    name: "Hyperextension Bench",
    name_es: "Banco de Hiperextensión",
    category: "accessory",
    description: "A 45-degree angled bench for back extensions targeting the erector spinae, glutes, and hamstrings.",
    description_es: "Banco en ángulo de 45 grados para extensiones de espalda que trabajan los erectores de la columna, glúteos e isquiotibiales.",
    muscle_groups: ["lower back", "glutes", "hamstrings"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Position hips on the pad so you can hinge freely at the waist.", instruction_es: "Posiciona las caderas en el cojín para poder hincar libremente en la cintura." },
      { step: 2, instruction: "Cross arms over chest, lower torso toward the floor.", instruction_es: "Cruza los brazos sobre el pecho, baja el torso hacia el suelo." },
      { step: 3, instruction: "Raise back up to neutral spine position using lower back and glutes.", instruction_es: "Levanta de vuelta a la posición neutral usando zona lumbar y glúteos." },
    ],
    safety_tips: ["Don't hyperextend beyond neutral spine", "Add weight once you master bodyweight form", "Avoid if you have lower back injuries"],
    safety_tips_es: ["No hiperextiendas más allá de la columna neutral", "Agrega peso cuando domines la forma con peso corporal", "Evita si tienes lesiones en la zona lumbar"],
  },
  {
    name: "Adjustable Bench",
    name_es: "Banco Ajustable",
    category: "accessory",
    description: "A versatile bench with multiple angle settings from flat to fully upright, suitable for dozens of dumbbell and barbell exercises.",
    description_es: "Banco versátil con múltiples ángulos desde plano hasta completamente vertical, adecuado para docenas de ejercicios con mancuernas y barra.",
    muscle_groups: ["chest", "shoulders", "triceps", "back"],
    difficulty: "beginner",
    tutorial_steps: [
      { step: 1, instruction: "Set bench to desired angle for your exercise.", instruction_es: "Ajusta el banco al ángulo deseado para tu ejercicio." },
      { step: 2, instruction: "Sit or lie on the bench and position yourself securely.", instruction_es: "Siéntate o acuéstate en el banco y posiciónate de forma segura." },
      { step: 3, instruction: "Perform the exercise with feet flat on the floor when possible.", instruction_es: "Realiza el ejercicio con los pies planos en el suelo cuando sea posible." },
    ],
    safety_tips: ["Ensure the back support is locked before loading", "Higher inclines reduce stability", "Wipe sweat from bench before and after use"],
    safety_tips_es: ["Asegura que el respaldo esté bloqueado antes de cargar", "Las inclinaciones más altas reducen la estabilidad", "Limpia el sudor del banco antes y después de usarlo"],
  },
  {
    name: "Captain's Chair",
    name_es: "Silla del Capitán",
    category: "accessory",
    description: "A padded arm-rest frame used for hanging knee raises, leg raises, and ab exercises without needing to grip a pull-up bar.",
    description_es: "Marco con apoyabrazos acolchados para elevar rodillas colgado, elevaciones de piernas y ejercicios abdominales.",
    muscle_groups: ["core", "hip flexors", "obliques"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Step up and rest forearms on the pads, back against the backrest.", instruction_es: "Sube y apoya los antebrazos en los cojines, espalda contra el respaldo." },
      { step: 2, instruction: "Lift knees toward your chest, contracting abs.", instruction_es: "Levanta las rodillas hacia el pecho, contrayendo el abdomen." },
      { step: 3, instruction: "Lower with control and repeat.", instruction_es: "Baja con control y repite." },
    ],
    safety_tips: ["Don't swing legs to generate momentum", "Keep lower back pressed against pad", "Straighten legs for harder leg raises"],
    safety_tips_es: ["No balancees las piernas para generar impulso", "Mantén la zona lumbar contra el respaldo", "Estira las piernas para elevaciones más difíciles"],
  },
  {
    name: "Landmine Attachment",
    name_es: "Anclaje Landmine",
    category: "accessory",
    description: "A floor-mounted sleeve that anchors one end of a barbell allowing rotational, pressing, and rowing movements from a pivot point.",
    description_es: "Manguito montado en el suelo que ancla un extremo de la barra permitiendo movimientos rotacionales, de empuje y de jaloneo desde un punto de pivote.",
    muscle_groups: ["core", "shoulders", "chest", "back", "glutes"],
    difficulty: "intermediate",
    tutorial_steps: [
      { step: 1, instruction: "Secure the barbell sleeve into the landmine anchor.", instruction_es: "Asegura el brazo de la barra en el anclaje landmine." },
      { step: 2, instruction: "Load the free end with appropriate weight.", instruction_es: "Carga el extremo libre con el peso adecuado." },
      { step: 3, instruction: "Grip the loaded end and perform your chosen movement.", instruction_es: "Agarra el extremo cargado y realiza el movimiento elegido." },
    ],
    safety_tips: ["Ensure the anchor is secured to the floor or under a plate", "Start light — leverage makes it feel heavier", "Keep core braced for rotational movements"],
    safety_tips_es: ["Asegura que el anclaje esté fijo al suelo o bajo un disco", "Empieza ligero — la palanca lo hace sentir más pesado", "Activa el core en movimientos rotacionales"],
  },
];

async function seed() {
  console.log(`Seeding ${equipment.length} equipment items...`);

  const { data, error } = await supabase
    .from("equipment")
    .upsert(equipment, { onConflict: "name", ignoreDuplicates: false })
    .select("id, name");

  if (error) {
    console.error("Seed error:", error.message, error.details ?? "");
    process.exit(1);
  }

  console.log(`✓ Seeded ${data?.length ?? 0} items`);
  data?.slice(0, 5).forEach((r) => console.log(" ", r.name));
  if ((data?.length ?? 0) > 5) console.log(`  ... and ${(data?.length ?? 0) - 5} more`);
}

seed().catch(console.error);
